api/urls.py
from . import views
from django.urls import path
app_name = "api"
urlpatterns = [
    path("dashBoard", views.dashBoard, name='dashBoard'),
    path("dashBoard_top100_case_time", views.dashBoard_top100_case_time, name='dashBoard_top100_case_time'),
    path("dashBoard_module_case", views.dashBoard_module_case, name='dashBoard_module_case'),
    path("dashBoard_top10_task", views.dashBoard_top10_task, name='dashBoard_top10_task'),
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('login_edit', views.login_edit, name='login_edit'),
    path('report_del', views.report_del, name='report_del'),
    path('download_log', views.download_log, name='download_log'),
    path('download_excel', views.download_excel, name='download_excel'),
    path('<int:id>/report_detail/', views.report_detail, name='report_detail'),
    path('module', views.module, name='module'),
    path('module_new', views.module_new, name='module_new'),
    path('module_edit', views.module_edit, name='module_edit'),
    path('module_del', views.module_del, name='module_del'),
    path('<int:id>/case/', views.case, name='case'),
    path('case_new', views.case_new, name='case_new'),
    path('case_new', views.case_new, name='case_new'),
    path('case_edit', views.case_edit, name='case_edit'),
    path('case_del', views.case_del, name='case_del'),
    path('<int:mid>/<int:cid>/fuzz/', views.fuzz, name='fuzz'), # 第一个id为模块id,第二个为用例id
    path('batch_fuzz', views.batch_fuzz, name='batch_fuzz'),
    path('fuzz_new', views.fuzz_new, name='fuzz_new'),
    path('fuzz_edit', views.fuzz_edit, name='fuzz_edit'),
    path('fuzz_del', views.fuzz_del, name='fuzz_del'),
    path('task', views.task, name="task"),
    path('task_new', views.task_new, name="task_new"),
    path('task_edit', views.task_edit, name="task_edit"),
    path('task_del', views.task_del, name="task_del"),
    path('task_run', views.task_run, name="task_run"),
    path('task_module_new', views.task_module_new, name="task_module_new"),
    path('<int:id>/task_module/', views.task_module, name="task_module"),
    path('task_module_edit', views.task_module_edit, name="task_module_edit"),
    path('task_module_del', views.task_module_del, name="task_module_del"),
    path('add', views.add, name="add")
]

djangoApi/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from djangoApi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ui/', include('ui.urls')),
    path('api/', include('api.urls')),
    path('', views.index, name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

]

ui/urls.py
# -*- coding=utf-8 -*-
__author__ = 'shikun'
__CreateAt__ = '2019/6/7-13:07'
from . import views
from django.urls import path
app_name = "ui"
urlpatterns = [
    path("dashBoard", views.dashBoard, name='dashBoard'),
    path("dashBoard_top100_case_time", views.dashBoard_top100_case_time, name='dashBoard_top100_case_time'),
    path("dashBoard_module_case", views.dashBoard_module_case, name='dashBoard_module_case'),
    path("dashBoard_top10_task", views.dashBoard_top10_task, name='dashBoard_top10_task'),
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('login_edit', views.login_edit, name='login_edit'),
    path('login_new', views.login_new, name='login_new'),
    path('login_del', views.login_del, name='login_del'),
    path('report_del', views.report_del, name='report_del'),
    path('download_log', views.download_log, name='download_log'),
    path('download_excel', views.download_excel, name='download_excel'),
    path('<int:id>/report_detail/', views.report_detail, name='report_detail'),
    path('module', views.module, name='module'),
    path('module_new', views.module_new, name='module_new'),
    path('module_edit', views.module_edit, name='module_edit'),
    path('module_del', views.module_del, name='module_del'),
    path('<int:mid>/case/', views.case, name='case'),
    path('case_new', views.case_new, name='case_new'),
    path('case_edit', views.case_edit, name='case_edit'),
    path('case_del', views.case_del, name='case_del'),
    path('<int:mid>/<int:cid>/step/', views.step, name='step'), # 第一个id为模块id,第二个为用例id
    path('step_new', views.step_new, name='step_new'),
    path('step_edit', views.step_edit, name='step_edit'),
    path('step_del', views.step_del, name='step_del'),
    path('<int:mid>/<int:cid>/check/', views.check, name='check'),  # 第一个id为模块id,第二个为用例id
    path('check_new', views.check_new, name='check_new'),
    path('check_edit', views.check_edit, name='check_edit'),
    path('check_del', views.check_del, name='check_del'),
    path('task', views.task, name="task"),
    path('task_new', views.task_new, name="task_new"),
    path('task_edit', views.task_edit, name="task_edit"),
    path('task_del', views.task_del, name="task_del"),
    path('task_run', views.task_run, name="task_run"),
    path('task_module_new', views.task_module_new, name="task_module_new"),
    path('<int:id>/task_module/', views.task_module, name="task_module"),
    path('task_module_edit', views.task_module_edit, name="task_module_edit"),
    path('task_module_del', views.task_module_del, name="task_module_del"),
    path("setting", views.setting, name="setting"),
    path("setting_edit", views.setting_edit, name="setting_edit"),
    path("common_case", views.common_case, name="common_case"),
    path("common_case_new", views.common_case_new, name="common_case_new"),
    path("common_case_edit", views.common_case_edit, name="common_case_edit"),
    path("common_case_del", views.common_case_del, name="common_case_del"),
    path("<int:id>/common_case_step/", views.common_case_step, name="common_case_step"),
    path("common_case_step_new", views.common_case_step_new, name="common_case_step_new"),
    path("common_case_step_edit", views.common_case_step_edit, name="common_case_step_edit"),
    path("common_case_step_del", views.common_case_step_del, name="common_case_step_del"),
    path("<int:mid>/<int:cid>/case_common_case/", views.case_common_case, name="case_common_case"),
    path("case_common_case_new", views.case_common_case_new, name="case_common_case_new"),
    path("case_common_case_edit", views.case_common_case_edit, name="case_common_case_edit"),
    path("case_common_case_del", views.case_common_case_del, name="case_common_case_del")

]

api/models.py
from django.db import models


class Login(models.Model):
    url = models.CharField(max_length=300)
    params = models.CharField(max_length=10000)

    def __str__(self):
        return self.url


class Report(models.Model):
    name = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sum_time = models.CharField(max_length=10)
    passed = models.IntegerField(default=0)
    failed = models.IntegerField(default=0)
    no_check = models.IntegerField(default=0)
    log = models.CharField(max_length=100, null=True)
    report_path = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ReportItem(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    protocol = models.CharField(max_length=10)
    method = models.CharField(max_length=10)
    params = models.CharField(max_length=1000)
    hope = models.CharField(max_length=100)
    sum_time = models.CharField(max_length=50)
    fact = models.CharField(max_length=10000)
    result = models.IntegerField(default=0)  # 0通过，-1失败，-2不检查
    code = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Module(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Case(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    protocol = models.CharField(max_length=10)
    method = models.CharField(max_length=10)
    params = models.CharField(max_length=1000)
    hope = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class FuzzCase(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='')
    url = models.CharField(max_length=100, default='')
    protocol = models.CharField(max_length=10, default='')
    method = models.CharField(max_length=10, default='')
    params = models.CharField(max_length=1000, default='')
    hope = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=100, default="")
    extend = models.IntegerField(default=0) # 0没有在测试，1测试中，2测试完成

# 关联任务和模块
class TaskModule(models.Model):
    mid = models.IntegerField(default=0)
    name = models.CharField(max_length=100, default="")
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

api/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from api import tasks
from api.base.BaseViewTaskModule import BaseViewTaskModule
from .base.BaseReport import BaseReport
from .base.BaseViewLogin import BaseViewLogin
from .base.BaseViewModule import BaseViewModule
from .base.BaseViewCase import BaseViewCase
from .base import BaseViewTask as bc
from .base.BaseViewDashBoard import BaseViewDashBoard
from .base.BaseViewFuzz import BaseViewFuzz
from .base.BaseViewTask import BaseViewTask


# =====dashBoard Start============

def dashBoard(request):
    return BaseViewDashBoard.dashBoard(request, "api/dashBoard.html")


def dashBoard_module_case(request):
    return BaseViewDashBoard.dashBoard_module_case(request)


def dashBoard_top10_task(request):
    return BaseViewDashBoard.dashBoard_top10_task(request)


def dashBoard_top100_case_time(request):
    return BaseViewDashBoard.dashBoard_top100_case_time(request)


# =====dashBoard End============

# ========测试报告 Start============

def index(request):
    page = request.GET.get('page')
    return BaseReport.index(request, page, "api/index.html")


@csrf_exempt
def report_del(request):
    return BaseReport.report_del(request.POST["rid"])


# 测试模块的用例列表接口
def report_detail(request, id):
    return BaseReport.report_detail(request, "api/reportDetail.html", id)


# 下载日志
@csrf_exempt
def download_log(request):
    return BaseReport.download_log(request.POST["log"])


# 下载excel
@csrf_exempt
def download_excel(request):
    return BaseReport.download_excel(request.POST["excel"])


# ========测试报告 End============


# 接口测试需要登录
def login(request):
    return BaseViewLogin.login(request, "api/login.html")


# 编辑登录接口参数
@csrf_exempt
def login_edit(request):
    url = request.POST["url"]
    params = request.POST["params"]
    return BaseViewLogin.login_edit({"url": url, "params": params})


# ========模块 Start============

# 模块列表
def module(request):
    return BaseViewModule.module(request, "api/module.html")


@csrf_exempt
def module_new(request):
    return BaseViewModule.module_new(request.POST["name"])


# 编辑模块
@csrf_exempt
def module_edit(request):
    m_id = request.POST["id"]
    name = request.POST["name"]
    return BaseViewModule.module_edit({"id": m_id, "name": name})


# 删除模块
@csrf_exempt
def module_del(request):
    m_id = request.POST["mid"]
    return BaseViewModule.module_del(m_id)


# ========模块 End============


# ========模块下用例 Start============


# 模块下的用例列表
def case(request, id):
    return BaseViewCase.case(request, 'api/case.html', id)


# 新建用例
@csrf_exempt
def case_new(request):
    id = request.POST["mid"]
    name = request.POST["name"]
    url = request.POST["url"]
    protocol = request.POST["protocol"]
    method = request.POST["method"]
    params = request.POST["params"]
    hope = request.POST.get("hope", "")
    return BaseViewCase.case_new(
        {"mid": id, "name": name, "url": url, "protocol": protocol, "method": method, "params": params, "hope": hope})


# 编辑用例
@csrf_exempt
def case_edit(request):
    c_id = request.POST["cid"]
    name = request.POST["name"]
    url = request.POST["url"]
    protocol = request.POST["protocol"]
    method = request.POST["method"]
    params = request.POST["params"]
    hope = request.POST["hope"]
    return BaseViewCase.case_edit(
        {"cid": c_id, "name": name, "url": url, "protocol": protocol, "method": method, "params": params, "hope": hope})


# 删除用例
@csrf_exempt
def case_del(request):
    return BaseViewCase.case_del(request.POST["cid"])

# ========模块下用例 End============

# ========模块的用例下的模糊用例 Start============


# 模糊用列表
def fuzz(request, mid, cid):
    return BaseViewFuzz.fuzz(request, "api/fuzz.html", mid, cid)


# 生成模糊用例
@csrf_exempt
def batch_fuzz(request):
    return BaseViewFuzz.batch_fuzz(request.POST["cid"])


# 新建模糊用例
@csrf_exempt
def fuzz_new(request):
    cid = request.POST["cid"]
    name = request.POST["name"]
    url = request.POST["url"]
    protocol = request.POST["protocol"]
    method = request.POST["method"]
    params = request.POST["params"]
    hope = request.POST.get("hope", "")
    return BaseViewFuzz.fuzz_new(
        {"cid": cid, "name": name, "url": url, "protocol": protocol, "method": method, "params": params, "hope": hope})


# 编辑模糊用例
@csrf_exempt
def fuzz_edit(request):
    fid = request.POST["fid"]
    name = request.POST["name"]
    url = request.POST["url"]
    protocol = request.POST["protocol"]
    method = request.POST["method"]
    params = request.POST["params"]
    hope = request.POST["hope"]
    return BaseViewFuzz.fuzz_edit(
        {"fid": fid, "name": name, "url": url, "protocol": protocol, "method": method, "params": params, "hope": hope})


# 删除模糊用例
@csrf_exempt
def fuzz_del(request):
    fid = request.POST["fid"]
    return BaseViewFuzz.fuzz_del(fid)


# ========模块的用例下的模糊用例 End============

# ========任务 Start============

def task(request):
    return BaseViewTask.tasks(request, "api/task.html")


@csrf_exempt
def task_new(request):
    name = request.POST["name"]
    return BaseViewTask.task_new(name)


@csrf_exempt
def task_edit(request):
    name = request.POST["name"]
    id = request.POST["id"]
    return BaseViewTask.task_edit({"name": name, "id": id})


@csrf_exempt
def task_del(request):
    id = request.POST["id"]
    return BaseViewTask.task_del(id)



@csrf_exempt
def task_run(request):
    bc.task_run.delay(request.POST["tid"])
    result = {'code': 0, 'msg': '这是一个后台任务'}
    return JsonResponse(result)


def add(request, *args, **kwargs):
    tasks.add.delay(1, 2)
    result = {'code': 0, 'msg': '这是一个后台任务'}
    return JsonResponse(result)

# ========任务 End============


# ========任务关联模块 Start============

def task_module(request, id):
    return BaseViewTaskModule.task_module(request, "api/taskModule.html", id)


@csrf_exempt
def task_module_new(request):
    tid = request.POST["tid"]
    mid = request.POST["mid"]
    # name = request.POST.getlist("mid")
    name = request.POST["name"]
    return BaseViewTaskModule.task_module_new(tid, name, mid)


@csrf_exempt
def task_module_edit(request):
    tmid = request.POST["tmid"]
    mid = request.POST["mid"]
    name = request.POST["name"]
    return BaseViewTaskModule.task_module_edit({"tmid": tmid, "mid": mid, "name": name})


@csrf_exempt
def task_module_del(request):
    return BaseViewTaskModule.task_module_del(request.POST["tmid"])
# ========任务关联模块 End============

api/templates/api/case.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

{% include 'api/header.html' %}
<body>
    {% include 'api/nav-top.html' %}
    <div class="container-fluid">
        <div class="row">
            {% include 'api/nav-left.html' %}
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <ol class="breadcrumb">
                      <li><a href="{% url 'api:module'  %}">模块</a></li>
                      <li><a href="{% url 'api:case' mid %}">用例</a></li>
                </ol>
                <h1 class="page-header">{{name}}--用例管理</h1>
                <button type="button" class="btn btn-primary" id="btn-module-new" data-toggle="modal" data-target="#modal-case">新建</button>
                <input type="hidden" id="mid" value="{{mid}}" />
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>用例名称</th>
                                <th>协议</th>
                                <th>url</th>
                                <th>方法</th>
                                <th>入参</th>
                                <th>期望值</th>
                                <th>操作</th>
                            </tr>
                                <td>{{i.url}}</td>
                        </thead>
                        <tbody>
                            {% if case_list %}
                            {% for i in  case_list %}
                            <tr id="{{i.id}}">
                                <td>{{i.name}}</td>
                                <td>{{i.protocol}}</td>
                                <td>{{i.url}}</td>
                                <td>{{i.method}}</td>
                                <td class="break-word-w300">{{i.params}}</td>
                                <td>{{i.hope}}</td>
                                <td>
                                    <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-case">
                                    <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                                    <a  class="btn btn-lg btn-primary" href="{% url 'api:fuzz' mid i.id %} "> 模糊用例</a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td>无数据</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% include 'api/del.html' %}
{% include 'api/edit-case.html' %}
{% include 'api/foot.html' %}
<script src=" {% static 'js/case.js'%}"></script>
</body>
</html>

api/templates/api/fuzz.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'api/header.html' %}
<body>
{% include 'api/nav-top.html' %}
<div class="container-fluid">
    <div class="row">
              {% include 'api/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
             <ol class="breadcrumb">
                  <li><a href="{% url 'api:module'  %}">模块</a></li>
                  <li><a href="{% url 'api:case' mid %}">用例</a></li>
                  <li><a href="{% url 'api:fuzz' mid case.id %} ">模糊用例</a></li>
                  <!--<li class="active">Data</li>-->
             </ol>
            <h1 class="page-header">{{case.name}}--模糊用例管理</h1>
             <button type="button" class="btn btn-primary" id="btn-new">新建</button>
             <button type="button" class="btn btn-primary" id="btn-fuzz-batch" >模糊生成</button>
            <input type="hidden" id="cid" value="{{case.id}}" />
            <input type="hidden" id="curl" value="{{case.url}}" />
            <input type="hidden" id="cname" value="{{case.name}}" />
            <input type="hidden" id="cpro" value="{{case.protocol}}" />
            <input type="hidden" id="cmethod" value="{{case.method}}" />
            <input type="hidden" id="cparams" value="{{case.params}}" />
            <input type="hidden" id="chope" value="{{case.hope}}" />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                         <th>用例名称</th>
                        <th>协议</th>
                        <th>url</th>
                        <th>方法</th>
                        <th>入参</th>
                        <th>期望值</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if fuzz_list %}
                    {% for i in  fuzz_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>{{i.protocol}}</td>
                        <td class="break-word-w300">{{i.url}}</td>
                        <td>{{i.method}}</td>
                        <td class="break-word-w300">{{i.params}}</td>
                        <td>{{i.hope}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-case">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>无数据</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'api/del.html' %}
{% include 'api/edit-fuzz.html' %}
{% include 'api/alert.html' %}
{% include 'api/foot.html' %}
<script src=" {% static 'js/common.js'%}"></script>
<script src=" {% static 'js/fuzz.js'%}"></script>


</body>
</html>

api/templates/api/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load pagetag %}
{% include 'api/header.html' %}

<body>
{% include 'api/nav-top.html' %}
<div class="container-fluid">
    <div class="row">
        {% include 'api/nav-left.html' %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">测试报告</h1>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>名字</th>
                        <th>开始时间</th>
                        <th>耗时</th>
                        <th>通过</th>
                        <th>失败</th>
                        <th>未检测</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if list_report %}
                    {% for i in  list_report %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>{{i.start_time}}</td>
                        <td>{{i.sum_time}}</td>
                        <td>{{i.passed}}</td>
                        <td>{{i.failed}}</td>
                        <td>{{i.no_check}}</td>
                        <td>
                            <!--<input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-case">-->
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                            <a  class="btn btn-lg btn-primary" href="{% url 'api:report_detail' i.id %} "> 查看详情</a>
                            <button  class="btn btn-lg btn-primary btn-log"  log="{{i.log}}"> 下载日志</button>
                            <button  class="btn btn-lg btn-primary btn-excel"  excel="{{i.report_path}}"> 下载报告</button>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>无数据</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if list_report.has_previous %}
                    <li>
                        <a href="?page={{ list_report.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    {%  for pg in list_report.paginator.page_range %}
                    {% circle_page list_report.number pg %}
                    {% endfor %}

                    {% if list_report.has_next %}
                    <li>
                        <a href="?page={{ list_report.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    </div>
</div>
{% include 'api/del.html' %}
{% include 'api/foot.html' %}
<script src=" {% static 'js/common.js'%}"></script>
<script src=" {% static 'js/index.js'%}"></script>
</body>
</html>

api/templates/api/module.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'api/header.html' %}

<body>
{% include 'api/nav-top.html' %}

<div class="container-fluid">
    <div class="row">
       {% include 'api/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1 class="page-header">模块</h1>
             <button type="button" class="btn btn-primary" id="btn-new" data-toggle="modal" data-target="#modal-module">新建</button>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>模块名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if module_list %}
                    {% for i in  module_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-module">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                            <a  class="btn btn-lg btn-primary" href="{% url 'api:case' i.id %} "> 用例管理</a>
                        </td>

                    </tr>
                    {% endfor %}

                    {% else %}
                    <tr>
                        <td>无数据</td>

                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'api/del.html' %}
{% include 'api/edit-module.html' %}
{% include 'api/foot.html' %}
<script src=" {% static 'js/common.js'%}"></script>
<script src=" {% static 'js/module.js'%}"></script>

</body>
</html>

api/templates/api/nav-left.html
<div class="col-sm-3 col-md-2 sidebar" id="nav-left">
    <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <li><a href="/api">测试报告</a></li>
        <li><a href="{% url 'api:dashBoard'  %}">DashBoard</a></li>
        <li><a href="{% url 'api:login'  %}">登录</a></li>
        <li><a href="{% url 'api:module'  %}">模块</a></li>
        <li><a href="{% url 'api:task'  %}">任务</a></li>

    </ul>
</div>

api/templates/api/reportDetail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'api/header.html' %}
<body>
{% include 'api/nav-top.html' %}

<div class="container-fluid">
    <div class="row">
          {% include 'api/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">{{name}}--测试报告</h1>
            <ol class="breadcrumb">
                  <li><a href="{% url 'api:index'  %}">DashBoard</a></li>
                  <li><a href="{% url 'api:report_detail' id %}">报告详情</a></li>
                  <!--<li class="active">Data</li>-->
             </ol>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>url</th>
                        <th>方法</th>
                        <th>入参</th>
                        <th>期望值</th>
                        <th>实际值</th>
                        <th>判定</th>
                        <th>响应码</th>
                        <th>耗时</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if case_list %}
                    {% for i in  case_list %}
                    <tr id="{{i.id}}">
                        <td class="break-word-w100">{{i.name}}</td>
                        <td class="break-word-w200">{{i.url}}</td>
                        <td>{{i.method}}</td>
                        <td class="break-word-w100">{{i.params}}</td>
                        <td>{{i.hope}}</td>
                        <td class="break-word-w200"> {{i.fact}}</td>
                        {% if i.result == 0 %}
                          <td>通过</td>
                         {% elif i.result == -1 %}
                             <td>失败</td>
                         {% else %}
                           <td>未检测</td>
                        {% endif %}
                        <td>{{i.code}}</td>
                        <td>{{i.sum_time}}</td>

                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>无数据</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% include 'api/foot.html' %}
<script src="{% static  'js/detail.js' %}"></script>

</body>
</html>