djangoApi/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from djangoApi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ui/', include('ui.urls')),
    path('api/', include('api.urls')),
    path('', views.index, name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

]

ui/urls.py
# -*- coding=utf-8 -*-
__author__ = 'shikun'
__CreateAt__ = '2019/6/7-13:07'
from . import views
from django.urls import path
app_name = "ui"
urlpatterns = [
    path("dashBoard", views.dashBoard, name='dashBoard'),
    path("dashBoard_top100_case_time", views.dashBoard_top100_case_time, name='dashBoard_top100_case_time'),
    path("dashBoard_module_case", views.dashBoard_module_case, name='dashBoard_module_case'),
    path("dashBoard_top10_task", views.dashBoard_top10_task, name='dashBoard_top10_task'),
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('login_edit', views.login_edit, name='login_edit'),
    path('login_new', views.login_new, name='login_new'),
    path('login_del', views.login_del, name='login_del'),
    path('report_del', views.report_del, name='report_del'),
    path('download_log', views.download_log, name='download_log'),
    path('download_excel', views.download_excel, name='download_excel'),
    path('<int:id>/report_detail/', views.report_detail, name='report_detail'),
    path('module', views.module, name='module'),
    path('module_new', views.module_new, name='module_new'),
    path('module_edit', views.module_edit, name='module_edit'),
    path('module_del', views.module_del, name='module_del'),
    path('<int:mid>/case/', views.case, name='case'),
    path('case_new', views.case_new, name='case_new'),
    path('case_edit', views.case_edit, name='case_edit'),
    path('case_del', views.case_del, name='case_del'),
    path('<int:mid>/<int:cid>/step/', views.step, name='step'), # 第一个id为模块id,第二个为用例id
    path('step_new', views.step_new, name='step_new'),
    path('step_edit', views.step_edit, name='step_edit'),
    path('step_del', views.step_del, name='step_del'),
    path('<int:mid>/<int:cid>/check/', views.check, name='check'),  # 第一个id为模块id,第二个为用例id
    path('check_new', views.check_new, name='check_new'),
    path('check_edit', views.check_edit, name='check_edit'),
    path('check_del', views.check_del, name='check_del'),
    path('task', views.task, name="task"),
    path('task_new', views.task_new, name="task_new"),
    path('task_edit', views.task_edit, name="task_edit"),
    path('task_del', views.task_del, name="task_del"),
    path('task_run', views.task_run, name="task_run"),
    path('task_module_new', views.task_module_new, name="task_module_new"),
    path('<int:id>/task_module/', views.task_module, name="task_module"),
    path('task_module_edit', views.task_module_edit, name="task_module_edit"),
    path('task_module_del', views.task_module_del, name="task_module_del"),
    path("setting", views.setting, name="setting"),
    path("setting_edit", views.setting_edit, name="setting_edit"),
    path("common_case", views.common_case, name="common_case"),
    path("common_case_new", views.common_case_new, name="common_case_new"),
    path("common_case_edit", views.common_case_edit, name="common_case_edit"),
    path("common_case_del", views.common_case_del, name="common_case_del"),
    path("<int:id>/common_case_step/", views.common_case_step, name="common_case_step"),
    path("common_case_step_new", views.common_case_step_new, name="common_case_step_new"),
    path("common_case_step_edit", views.common_case_step_edit, name="common_case_step_edit"),
    path("common_case_step_del", views.common_case_step_del, name="common_case_step_del"),
    path("<int:mid>/<int:cid>/case_common_case/", views.case_common_case, name="case_common_case"),
    path("case_common_case_new", views.case_common_case_new, name="case_common_case_new"),
    path("case_common_case_edit", views.case_common_case_edit, name="case_common_case_edit"),
    path("case_common_case_del", views.case_common_case_del, name="case_common_case_del")

]

ui/models.py
# -*- coding=utf-8 -*-
__author__ = 'shikun'
__CreateAt__ = '2019/6/7-13:07'
from django.db import models


class Setting(models.Model):
    login_url = models.CharField(max_length=200)
    home_url = models.CharField(max_length=200)


class Login(models.Model):
    element_info = models.CharField(max_length=300)
    find_type = models.CharField(max_length=300)
    operate_type = models.CharField(max_length=100)
    extend = models.CharField(max_length=100)
    sort = models.IntegerField(default=0)
    name = models.CharField(max_length=100)


class Report(models.Model):
    name = models.CharField(max_length=100)
    start_time = models.CharField(max_length=100)
    sum_time = models.CharField(max_length=10)
    passed = models.IntegerField(default=0)
    failed = models.IntegerField(default=0)
    no_check = models.IntegerField(default=0)
    log = models.CharField(max_length=100, null=True)
    report_path = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ReportItem(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    step = models.CharField(max_length=300)
    hope = models.CharField(max_length=100)
    sum_time = models.CharField(max_length=50)
    result = models.IntegerField(default=0)  # 0通过，-1失败，-2不检查
    img = models.CharField(max_length=100, default="")
    extend = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.name


class Module(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Case(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)


class Steps(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    element_info = models.CharField(max_length=300)
    find_type = models.CharField(max_length=300)
    operate_type = models.CharField(max_length=100)
    extend = models.CharField(max_length=100)
    sort = models.IntegerField(default=0)


class Checks(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    element_info = models.CharField(max_length=300)
    find_type = models.CharField(max_length=300)
    operate_type = models.CharField(max_length=100)
    extend = models.CharField(max_length=100)


class Task(models.Model):
    name = models.CharField(max_length=100, default="")


# 关联任务和模块
class TaskModule(models.Model):
    mid = models.IntegerField(default=0)
    name = models.CharField(max_length=100, default="")
    task = models.ForeignKey(Task, on_delete=models.CASCADE)


# 公共用例
class CommonCase(models.Model):
    name = models.CharField(max_length=100, default="")


# 公共用例步骤
class CommonCaseStep(models.Model):
    commonCase = models.ForeignKey(CommonCase, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    element_info = models.CharField(max_length=300)
    find_type = models.CharField(max_length=300)
    operate_type = models.CharField(max_length=100)
    extend = models.CharField(max_length=100)
    sort = models.IntegerField(default=0)


# 用例关联公共用例
class CaseCommonCase(models.Model):
    cc_id = models.IntegerField(default=0)  # 公共用例 的id
    name = models.CharField(max_length=100)
    sort = models.IntegerField(default=0)
    case = models.ForeignKey(Case, on_delete=models.CASCADE, default=0)

ui/views.py
# -*- coding=utf-8 -*-
__author__ = 'shikun'
__CreateAt__ = '2019/6/7-13:07'
from django.views.decorators.csrf import csrf_exempt
from ui.base.BaseViewTaskModule import BaseViewTaskModule
from .base.BaseViewDashBoard import BaseViewDashBoard
from .base.BaseViewLogin import BaseViewLogin
from .base.BaseViewModule import BaseViewModule
from .base.BaseViewCase import BaseViewCase
from .base.BaseViewTask import BaseViewTask
from .base.BaseViewSetting import BaseViewSetting
from .base.BaseViewStep import BaseViewStep
from .base.BaseViewCheck import BaseViewCheck
from .base.BaseReport import BaseReport
from .base.BaseViewCommonCase import BaseViewCommonCase
from .base.BaseViewCommonCaseStep import BaseViewCommonCaseStep
from .base.BaseViewCaseCommonCase import BaseViewCaseCommonCase


def setting(request):
    return BaseViewSetting.setting(request, "ui/setting.html")


@csrf_exempt
def setting_edit(request):
    home_url = request.POST["home_url"]
    login_url = request.POST["login_url"]
    kw = {"home_url": home_url, "login_url": login_url}
    return BaseViewSetting.setting_edit(kw)


# ============dashBoard Start==============
def dashBoard(request):
    return BaseViewDashBoard.dashBoard(request, "ui/dashBoard.html")


def dashBoard_module_case(request):
    return BaseViewDashBoard.dashBoard_module_case(request)


def dashBoard_top10_task(request):
    return BaseViewDashBoard.dashBoard_top10_task(request)


def dashBoard_top100_case_time(request):
    return BaseViewDashBoard.dashBoard_top100_case_time(request)


# =========dashBoard End=========


# ========测试报告 Start============
def index(request):
    page = request.GET.get('page')
    return BaseReport.index(request, page, "ui/index.html")


@csrf_exempt
def report_del(request):
    return BaseReport.report_del(request.POST["rid"])


# 测试模块的用例列表接口
def report_detail(request, id):
    return BaseReport.report_detail(request, "ui/reportDetail.html", id)


# 下载日志
@csrf_exempt
def download_log(request):
    return BaseReport.download_log(request.POST["log"])


# 下载excel
@csrf_exempt
def download_excel(request):
    return BaseReport.download_excel(request.POST["excel"])


# ===========测试报告 End============

# =====登录的用例 Start======
def login(request):
    return BaseViewLogin.login(request, "ui/login.html")


@csrf_exempt
def login_new(request):
    find_type = request.POST["find_type"]
    element_info = request.POST["element_info"]
    operate_type = request.POST["operate_type"]
    extend = request.POST["extend"]
    sort = request.POST["sort"]
    name = request.POST["name"]
    kw = {"find_type": find_type, "element_info": element_info, "name": name, "operate_type": operate_type,
          "extend": extend, "sort": sort}
    return BaseViewLogin.login_new(kw)


# 编辑登录接口参数
@csrf_exempt
def login_edit(request):
    id = request.POST["id"]
    find_type = request.POST["find_type"]
    element_info = request.POST["element_info"]
    operate_type = request.POST["operate_type"]
    extend = request.POST["extend"]
    sort = request.POST["sort"]
    name = request.POST["name"]
    app = {"id": id, "find_type": find_type, "element_info": element_info, "operate_type": operate_type,
           "extend": extend, "sort": sort, "name": name}
    return BaseViewLogin.login_edit(app)


@csrf_exempt
def login_del(request):
    return BaseViewLogin.login_del(request.POST["id"])


# ====登录 End==================


# =======模块 Start====================

# 模块列表
def module(request):
    return BaseViewModule.module(request, "ui/module.html")


@csrf_exempt
def module_new(request):
    return BaseViewModule.module_new(request.POST["name"])


# 编辑模块
@csrf_exempt
def module_edit(request):
    m_id = request.POST["id"]
    name = request.POST["name"]
    return BaseViewModule.module_edit({"id": m_id, "name": name})


# 删除模块
@csrf_exempt
def module_del(request):
    id = request.POST["id"]
    return BaseViewModule.module_del(id)


# ======模块 End==============


# ======模块下用例 Start=================
# 模块下的用例列表
def case(request, mid):
    return BaseViewCase.case(request, 'ui/case.html', mid)


# 新建用例
@csrf_exempt
def case_new(request):
    mid = request.POST["mid"]
    name = request.POST["name"]
    return BaseViewCase.case_new({"mid": mid, "name": name})


# 编辑用例
@csrf_exempt
def case_edit(request):
    c_id = request.POST["cid"]
    name = request.POST["name"]

    return BaseViewCase.case_edit(
        {"cid": c_id, "name": name})


# 删除用例
@csrf_exempt
def case_del(request):
    return BaseViewCase.case_del(request.POST["cid"])


# =====模块下用例 End===================

# ====用例下步骤 Start=====================

# 用例下的检查点
def check(request, mid, cid):
    return BaseViewCheck.check(request, "ui/check.html", mid, cid)


# 新建
@csrf_exempt
def check_new(request):
    cid = request.POST["cid"]
    name = request.POST["name"]
    element_info = request.POST["element_info"]
    find_type = request.POST["find_type"]
    operate_type = request.POST["operate_type"]
    extend = request.POST.get("extend", "")
    kw = {"cid": cid, "name": name, "element_info": element_info, "find_type": find_type, "operate_type": operate_type,
          "extend": extend}
    return BaseViewCheck.check_new(kw)


@csrf_exempt
def check_edit(request):
    chid = request.POST["chid"]
    name = request.POST["name"]
    element_info = request.POST["element_info"]
    find_type = request.POST["find_type"]
    operate_type = request.POST["operate_type"]
    extend = request.POST.get("extend", "")
    kw = {"chid": chid, "name": name, "element_info": element_info, "find_type": find_type,
          "operate_type": operate_type,
          "extend": extend}
    return BaseViewCheck.check_edit(kw)


@csrf_exempt
def check_del(request):
    return BaseViewCheck.check_del(request.POST["chid"])


# ========用例下检查点 End=====================


# =========用例下步骤 Start=============
# 用例下的步骤
def step(request, mid, cid):
    return BaseViewStep.step(request, "ui/step.html", mid, cid)


# 新建步骤
@csrf_exempt
def step_new(request):
    cid = request.POST["cid"]
    name = request.POST["name"]
    element_info = request.POST["element_info"]
    find_type = request.POST["find_type"]
    operate_type = request.POST["operate_type"]
    extend = request.POST.get("extend", "无")
    sort = request.POST.get("sort", 0)
    kw = {"cid": cid, "name": name, "element_info": element_info, "find_type": find_type, "operate_type": operate_type,
          "extend": extend, "sort": sort}
    return BaseViewStep.step_new(kw)


@csrf_exempt
def step_edit(request):
    sid = request.POST["sid"]
    name = request.POST["name"]
    element_info = request.POST["element_info"]
    find_type = request.POST["find_type"]
    operate_type = request.POST["operate_type"]
    extend = request.POST.get("extend", "无")
    sort = request.POST.get("sort", "")

    kw = {"sid": sid, "name": name, "element_info": element_info, "find_type": find_type, "operate_type": operate_type,
          "extend": extend, "sort": sort}
    return BaseViewStep.step_edit(kw)


@csrf_exempt
def step_del(request):
    return BaseViewStep.step_del(request.POST["sid"])


# ======用例下步骤 End================

# ========任务 Start=================

def task(request):
    return BaseViewTask.task(request, "ui/task.html")


@csrf_exempt
def task_new(request):
    name = request.POST["name"]
    return BaseViewTask.task_new(name)


@csrf_exempt
def task_edit(request):
    name = request.POST["name"]
    id = request.POST["id"]
    return BaseViewTask.task_edit({"name": name, "id": id})


@csrf_exempt
def task_del(request):
    id = request.POST["id"]
    return BaseViewTask.task_del(id)


@csrf_exempt
def task_run(request):
    return BaseViewTask.task_run(request.POST["tid"])


# =======任务 End================


# ======任务关联模块=================
def task_module(request, id):
    return BaseViewTaskModule.task_module(request, "ui/taskModule.html", id)


@csrf_exempt
def task_module_new(request):
    tid = request.POST["tid"]
    mid = request.POST["mid"]
    # name = request.POST.getlist("mid")
    name = request.POST["name"]
    return BaseViewTaskModule.task_module_new(tid, name, mid)


@csrf_exempt
def task_module_edit(request):
    tmid = request.POST["tmid"]
    mid = request.POST["mid"]
    name = request.POST["name"]
    return BaseViewTaskModule.task_module_edit({"tmid": tmid, "mid": mid, "name": name})


@csrf_exempt
def task_module_del(request):
    return BaseViewTaskModule.task_module_del(request.POST["tmid"])


# ========任务关联模块 End====================


# =======公用用例 Start==========

def common_case(request):
    return BaseViewCommonCase.common_case(request, "ui/common-case.html")


@csrf_exempt
def common_case_new(request):
    return BaseViewCommonCase.common_case_new(request.POST["name"])


@csrf_exempt
def common_case_edit(request):
    id = request.POST["id"]
    name = request.POST["name"]
    return BaseViewCommonCase.common_case_edit({"id": id, "name": name})


@csrf_exempt
def common_case_del(request):
    return BaseViewCommonCase.common_case_del(request.POST["id"])


# =========公共用例 end==============

# =======公共用例下的步骤==========
def common_case_step(request, id):
    # id 是公共用例表的id,common_case
    return BaseViewCommonCaseStep.common_case_step(request, "ui/common-case-step.html", id)


@csrf_exempt
def common_case_step_new(request):
    cc_id = request.POST["cc_id"]
    name = request.POST["name"]
    element_info = request.POST["element_info"]
    find_type = request.POST["find_type"]
    operate_type = request.POST["operate_type"]
    extend = request.POST.get("extend", "0")
    sort = request.POST.get("sort", 0)

    kw = {"cc_id": cc_id, "name": name, "element_info": element_info, "find_type": find_type,
          "operate_type": operate_type,
          "extend": extend, "sort": sort}
    return BaseViewCommonCaseStep.common_case_step_new(kw)


@csrf_exempt
def common_case_step_edit(request):
    ccs_id = request.POST["ccs_id"]
    name = request.POST["name"]

ui/templates/ui/alert.html
<div class="modal fade " id="modal-operate">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" datadismiss="modal"
                        aria-hidden="true">×</button>
                <h4 class="modal-title">提示框</h4>
            </div>
            <div class="modal-body">
                <p>操作中.....</p>
            </div>
            <!--<div class="modal-footer">-->
                <!--<button type="button" class="btn btn-default" datadismiss="modal" id="btn-modal-confirm">-->
                    <!--确定</button>-->
                <!--<button type="button" class="btn btn-primary">取消-->
                <!--</button>-->
            <!--</div>-->
        </div>
    </div>
</div>

ui/templates/ui/common-case-step.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'ui/header.html' %}
<body>
{% include 'ui/nav-top.html' %}
<div class="container-fluid">
    <div class="row">
         {% include 'ui/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
             <ol class="breadcrumb">
                  <li><a href="{% url 'ui:common_case'  %}">公共用例</a></li>
                  <li><a href="{% url 'ui:common_case_step' cc_id  %}">{{name}}</a></li>
                  <li class="active">步骤管理</li>
             </ol>
            <h1 class="page-header">{{name}}--步骤管理</h1>
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-common-case-step" id="btn-new">新建</button>
            <input type="hidden" id="cc_id" value="{{cc_id}}" />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                         <th>名字</th>
                        <th>元素</th>
                        <th>查找类型</th>
                        <th>操作方法</th>
                        <th>扩展</th>
                        <th>排序</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if step_list %}
                    {% for i in  step_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>{{i.element_info}}</td>
                        <td>{{i.find_type}}</td>
                        <td>{{i.operate_type}}</td>
                        <td>{{i.extend}}</td>
                        <td>{{i.sort}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-common-case-step">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>无数据</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'ui/del.html' %}
{% include 'ui/edit-common-case-step.html' %}
{% include 'ui/foot.html' %}
<script src=" /static/js/common1.js"></script>
<script src=" /static/js/common-case-step.js"></script>


</body>
</html>

ui/templates/ui/common-case.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'ui/header.html' %}

<body>
{% include 'ui/nav-top.html' %}

<div class="container-fluid">
    <div class="row">
             {% include 'ui/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">公共用例</h1>
             <button type="button" class="btn btn-primary" id="btn-new" data-toggle="modal" data-target="#modal-common-case">新建</button>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>模块名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if case_list %}
                    {% for i in  case_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-common-case">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                            <a  class="btn btn-lg btn-primary" href="{% url 'ui:common_case_step' i.id %} "> 步骤管理</a>
                        </td>

                    </tr>
                    {% endfor %}

                    {% else %}
                    <tr>
                        <td>无数据</td>

                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'ui/del.html' %}
{% include 'ui/edit-common-case.html' %}
{% include 'ui/alert.html' %}
{% include 'ui/foot.html' %}
<script src="/static/js/common1.js"></script>
<script src="/static/js/common-case.js"></script>

</body>
</html>

ui/templates/ui/del.html
<div class="modal fade " id="modal-del">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">删除提示框</h4>
            </div>
            <div class="modal-body">
                <p>确定要删除吗？</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" datadismiss="modal" id="btn-modal-confirm">
                    确定</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">取消
                </button>
            </div>
        </div>
    </div>
</div>

ui/templates/ui/module.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'ui/header.html' %}

<body>
{% include 'ui/nav-top.html' %}

<div class="container-fluid">
    <div class="row">
             {% include 'ui/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">模块</h1>
             <button type="button" class="btn btn-primary" id="btn-new" data-toggle="modal" data-target="#modal-module">新建</button>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>模块名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if module_list %}
                    {% for i in  module_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-module">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                            <a  class="btn btn-lg btn-primary" href="{% url 'ui:case' i.id %} "> 用例管理</a>
                        </td>

                    </tr>
                    {% endfor %}

                    {% else %}
                    <tr>
                        <td>无数据</td>

                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'ui/del.html' %}
{% include 'ui/edit-module.html' %}
{% include 'ui/alert.html' %}
{% include 'ui/foot.html' %}
<script src=" {% static 'js/common1.js'%}"></script>
<script src=" {% static 'js/module1.js'%}"></script>

</body>
</html>

ui/templates/ui/nav-left.html
<div class="col-sm-3 col-md-2 sidebar" id="nav-left">
    <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <li><a href="/ui" >测试报告</a></li>
        <li><a href="{% url 'ui:dashBoard'  %}">DashBoard</a></li>
        <li><a href="{% url 'ui:setting'  %}">设置</a></li>
        <li><a href="{% url 'ui:login'  %}">登录</a></li>
        <li><a href="{% url 'ui:common_case'  %}">公共用例</a></li>
        <li><a href="{% url 'ui:module'  %}">模块</a></li>
        <li><a href="{% url 'ui:task'  %}">任务</a></li>
    </ul>
</div>

ui/templates/ui/step.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include 'ui/header.html' %}
<body>
{% include 'ui/nav-top.html' %}
<div class="container-fluid">
    <div class="row">
         {% include 'ui/nav-left.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
             <ol class="breadcrumb">
                  <li><a href="{% url 'ui:module'  %}">模块</a></li>
                  <li><a href="{% url 'ui:case' mid %}">用例</a></li>
                  <li class="active">步骤管理</li>
             </ol>
            <h1 class="page-header">{{name}}--步骤管理</h1>
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-step" id="btn-new">新建</button>
             <a href="{% url 'ui:case_common_case' mid cid %}" class="btn btn-primary">关联公共用例</a>
            <input type="hidden" id="cid" value="{{cid}}" />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                         <th>名字</th>
                        <th>元素</th>
                        <th>查找类型</th>
                        <th>操作方法</th>
                        <th>扩展</th>
                        <th>排序</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if step_list %}
                    {% for i in  step_list %}
                    <tr id="{{i.id}}">
                        <td>{{i.name}}</td>
                        <td>{{i.element_info}}</td>
                        <td>{{i.find_type}}</td>
                        <td>{{i.operate_type}}</td>
                        <td>{{i.extend}}</td>
                        <td>{{i.sort}}</td>
                        <td>
                            <input type="button" class="btn btn-lg btn-primary btn-edit" value="编辑"  data-toggle="modal" data-target="#modal-step">
                            <input type="button"  class="btn btn-lg btn-primary btn-del" value="删除">
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>无数据</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% include 'ui/del.html' %}
{% include 'ui/edit-step.html' %}
{% include 'ui/foot.html' %}
<script src=" {% static 'js/common1.js'%}"></script>
<script src=" {% static 'js/step.js'%}"></script>


</body>
</html>